const AfterNth = require('./AfterNth');
const Anything = require('./Anything');
const BeforeNth = require('./BeforeNth');
const EndWith = require('./EndWith');
const EndWithNon = require('./EndWithNon');
const Exclude = require('./Exclude');
const FirstN = require('./FirstN');
const Has = require('./Has');
const HasN = require('./HasN');
const IsAlphabet = require('./IsAlphabet');
const IsChinese = require('./IsChinese');
const IsEmail = require('./IsEmail');
const IsInt = require('./IsInt');
const IsIP = require('./IsIP');
const IsLowerCase = require('./IsLowerCase');
const IsUpperCase = require('./IsUpperCase');
const IsWord = require('./IsWord');
const LastN = require('./LastN');
const LenBtw = require('./LenBtw');
const LenEq = require('./LenEq');
const LenGeq = require('./LenGeq');
const LenGt = require('./LenGt');
const LenLeq = require('./LenLeq');
const LenLt = require('./LenLt');
const QuoteBy = require('./QuoteBy');
const Regex = require('./Regex');
const StartWith = require('./StartWith');
const StartWithNon = require('./StartWithNon');

module.exports = {
    AfterNth: (...args) => new AfterNth(...args),
    Anything: (...args) => new Anything(...args),
    BeforeNth: (...args) => new BeforeNth(...args),
    EndWith: (...args) => new EndWith(...args),
    EndWithNon: (...args) => new EndWithNon(...args),
    Exclude: (...args) => new Exclude(...args),
    FirstN: (...args) => new FirstN(...args),
    Has: (...args) => new Has(...args),
    HasN: (...args) => new HasN(...args),
    IsAlphabet: (...args) => new IsAlphabet(...args),
    IsChinese: (...args) => new IsChinese(...args),
    IsEmail: (...args) => new IsEmail(...args),
    IsInt: (...args) => new IsInt(...args),
    IsIP: (...args) => new IsIP(...args),
    IsLowerCase: (...args) => new IsLowerCase(...args),
    IsUpperCase: (...args) => new IsUpperCase(...args),
    IsWord: (...args) => new IsWord(...args),
    LastN: (...args) => new LastN(...args),
    LenBtw: (...args) => new LenBtw(...args),
    LenEq: (...args) => new LenEq(...args),
    LenGeq: (...args) => new LenGeq(...args),
    LenGt: (...args) => new LenGt(...args),
    LenLeq: (...args) => new LenLeq(...args),
    LenLt: (...args) => new LenLt(...args),
    QuoteBy: (...args) => new QuoteBy(...args),
    Regex: (...args) => new Regex(...args),
    StartWith: (...args) => new StartWith(...args),
    StartWithNon: (...args) => new StartWithNon(...args),
}

// const fs = require('fs');
// const dirs = fs.readdirSync('./');
// const arr = dirs
//     .map(dir => dir.replace('.js', ''))
//     .filter(dir => dir !== 'index' && dir !== 'Validator');

// for (const dir of arr)
//     console.log(`const ${dir} = require('./${dir}');`);
//     console.log(`    ${dir}: (...args) => new ${dir}(...args),`);